### ISSUE TITLE
Support for different move notations

### ISSUE THREAD

**Issue by scaljeri** [davidlacarta/chess#1]
Thanks a lot for this very nice library. As far as I understand, the only way to add a move would be

    chess.move('e2','e4');

However, there a couple of notations, for example, Stockfish and Lc0 produce moves like `e2e4` and if you play at **chess.com** they notate it like `e4` or `Nf3` etc. 

I've used [chess.js](https://github.com/jhlywa/chess.js) before and that lib has a very extended support for moves, but that project seems dead to me. Any plans to support that?

**Comment by davidlacarta** [comment]
@scaljeri that's right, the only way to move at the moment is that.

The next feature to add would be [standard algebraic notation (SAN)](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)).

For example:
```
chess.move('e4');
chess.move('e5');
chess.move('Nf3');
...
chess.move('Bxe5');
```

**Comment by davidlacarta** [comment]
Added [standard algebraic notation (SAN)](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)).

```js
chess.move('e4');
chess.move('e5');
chess.move('Nf3');
...
chess.move('Bxe5');
```

**Comment by scaljeri** [comment]
Thanks for adding this already. I noticed two issues (I think)

First one is castling. Consider the following

    import { Chess } from 'chess-base';
    const chess = new Chess('rnbq1rk1/p3bpp1/1p2pn1p/2ppN3/3P3B/2N1P3/PPP1BPPP/R2QK2R w KQ c6 0 9');

![image](https://user-images.githubusercontent.com/1078741/62013063-207c4c00-b18e-11e9-92eb-c371f9b2c9c2.png)

When I try to castle

     chess.move('e1', 'g1'); // --> Throws error

It seems that you can only castle with

    chess.castlingKing();  // or
    chess.move('O-O');    // <- very nice!!

It would be nice to support 'e1', 'g1' notation (I get this notation from chess engines)

The other issue I noticed is with the following fen string `8/P7/7k/8/8/8/K7/8 w - - 0 61`

![image](https://user-images.githubusercontent.com/1078741/62013052-0e021280-b18e-11e9-93b0-aff50bc997cf.png)

If the pawn moves from `a7` to `a8` you cannot do

    chess.move('a8', 'q');

but instead you have to do

    chess.move('a7', 'a8', 'q');

Hope this makes any sense, cheers!
