### ISSUE TITLE
Half castling SAN

### ISSUE THREAD

**Issue by scaljeri** [davidlacarta/chess#3]
Thanks for adding this already. I noticed two issues (I think)

First one is castling. Consider the following

    import { Chess } from 'chess-base';
    const chess = new Chess('rnbq1rk1/p3bpp1/1p2pn1p/2ppN3/3P3B/2N1P3/PPP1BPPP/R2QK2R w KQ c6 0 9');

![image](https://user-images.githubusercontent.com/1078741/62013063-207c4c00-b18e-11e9-92eb-c371f9b2c9c2.png)

When I try to castle

     chess.move('e1', 'g1'); // --> Throws error

It seems that you can only castle with

    chess.castlingKing();  // or
    chess.move('O-O');    // <- very nice!!

It would be nice to support 'e1', 'g1' notation (I get this notation from chess engines)

The other issue I noticed is with the following fen string `8/P7/7k/8/8/8/K7/8 w - - 0 61`

![image](https://user-images.githubusercontent.com/1078741/62013052-0e021280-b18e-11e9-93b0-aff50bc997cf.png)

If the pawn moves from `a7` to `a8` you cannot do

    chess.move('a8', 'q');

but instead you have to do

    chess.move('a7', 'a8', 'q');

Hope this makes any sense, cheers!

**Comment by davidlacarta** [comment]
About castling, I've added half castling for SAN. I will publish new library version soon.
```js
chess.move('e1g1');
```

About pawn promotion, notation would be 
```js
chess.move('a8Q');
// or
chess.move('a7', 'a8', 'q');
```

**Comment by scaljeri** [comment]
One last thing, the pawn promotion, is it possible to make the pawn promotion-char case insensitive? Now it throws 

     Invalid SAN: a8q

From chess engines like Stockfish and Lc0 I get notations like

    a7a8q

**Comment by davidlacarta** [comment]
Added half castling for SAN [v1.2.0](https://github.com/davidlacarta/chess/releases/tag/v1.2.0)
```js
chess.move('e1g1');
```

**Comment by scaljeri** [comment]
I just ran into the following issue

    const chess = require('chess-base');
    const c = new chess.Chess(); 

    c.move('e2e4');
    c.move('e7e5');
    c.move('f1d3');  // --> error
    c.move('d7d5');
    c.move('g1f3');  // --> error
    c.move('c7c5');
    c.move('e1g1');

Turns out that when its not a pawn, you cannot do `c.move('f1d3')` but you can do `c.move('f1', d3')`. Problem is that in theory I can split the move, but then I get stuck on castling, because `c.move('e1', 'g1') doesn't work

**Comment by davidlacarta** [comment]
```"f1d3"``` is invalid SAN, should be ```"Bd3"``` (move a bishop to d3) [Standard Algebraic Notation](https://en.wikipedia.org/wiki/Algebraic_notation_(chess))

> Each move of a piece is indicated by the piece's uppercase letter, plus the coordinate of the destination square. For example, Be5 (move a bishop to e5), Nf3 (move a knight to f3). For pawn moves, a letter indicating pawn is not used, only the destination square is given. For example, c5 (move a pawn to c5).

```js
const chess = new Chess("rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2");
chess.move("f1d3"); // -> Thrown: 'Invalid SAN: f1d3'
```
There are two ways to make a move:

1. Coordinate Notation
```js
const chess = new Chess("rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2");

// chess.move([from], [to], [promotion_type]);
chess.move("f1", "d3"); 
```
2. Standard Algebraic Notation (SAN)
```js
const chess = new Chess("rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq e6 0 2");

// chess.move([movement_SAN]);
chess.move("Bd3");
```
If "move" function take 1 parameter, will take it as SAN, if it takes more than one parameter, will take them as Coordinate Notation.

**Comment by scaljeri** [comment]
Ok, thats clear, but is `e2e4` SAN? and `e1g1`?

**Comment by davidlacarta** [comment]
There is no strict SAN validation. Some invalid or incomplete movements will work and others will not. But all valid full SAN movements should work.

```e2e4``` and ```e1g1``` are invalid SAN, but they work.
