### ISSUE TITLE
Error with caslting king-side

### ISSUE THREAD

**Issue by scaljeri** [davidlacarta/chess#4]
I just ran into the following situation with castling. The fen is

     1r2k2r/ppp2ppp/8/3N1b2/3n4/8/PP2PPPP/R3KB1R w KQk - 0 13

![image](https://user-images.githubusercontent.com/1078741/70868972-53c94700-1f86-11ea-881e-1af95fab5353.png)

([source](https://lichess.org/editor/1r2k2r/ppp2ppp/8/3N1b2/3n4/8/PP2PPPP/R3KB1R_w_KQk_-_0_1))

White to move, which does: e1c1

    import { Chess } from 'chess-base';
    const fen = '1r2k2r/ppp2ppp/8/3N1b2/3n4/8/PP2PPPP/R3KB1R w KQk - 0 13';
    const chess = new Chess(fen);
    chess.move('e1c1');

Which gives an error ending with: `castling target`

We've discussed this before ( https://github.com/davidlacarta/chess/issues/3 ) and I must say that I find the castling notation very confusing. Any ideas what might be the problem in this situation?

**Comment by davidlacarta** [comment]
It's a bug 👍 

```
// piece.js
const CASTLING_COLUMN_SAFE = {
  k: ["e", "f", "g"],
  q: ["b", "c", "d", "e"]
};
```

Column b shouldn't be there.

**Comment by davidlacarta** [comment]
Thanks @scaljeri 👍
